### PR TITLE
Fix CCE when retrieving unsupported variable retrieval

### LINKED ISSUE #500: Getting a class cast exception when I ran a simple C2C example
**Description:**
I had a simple HTTP client implemented in Ballerina, which works fine. But recently, I keep receiving the following error when I try to execute a simple `bal build`.

```sh
error: compilation failed: The compiler extension in package 'ballerina:cloud:2.1.2' failed to complete. class io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode cannot be cast to class io.ballerina.compiler.syntax.tree.MappingConstructorExpressionNode (io.ballerina.compiler.syntax.tree.SimpleNameReferenceNode and io.ballerina.compiler.syntax.tree.MappingConstructorExpressionNode are in unnamed module of loader 'app')
```

I suspect the recent 2.1.2 release caused this.

**Steps to reproduce:**
Try a simple HTTP client with C2C.

**Affected Versions:**
- Ballerina 2201.0.1 (Swan Lake)
- macOS

### PR DESCRIPTION
**Pull request by xlight05**
## Purpose
$Subject. Adds a diagnostic and prevents crashing.
With this PR, entire http client record should have c2c supported syntax. otherwise the config map won't be created

Resolves #500

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: c2c-util/src/main/java/io/ballerina/c2c/util/C2CVisitor.java [hunk 1]
```diff
@@ -431,23 +431,34 @@ public void visit(ServiceDeclarationNode serviceDeclarationNode) {
...
+    private Optional<MutualSSLConfig> getMutualSSLConfig(ExpressionNode expressionNode) {
         MutualSSLConfig mutualSSLConfig = new MutualSSLConfig();
         if (expressionNode.kind() == SyntaxKind.STRING_LITERAL) {
             mutualSSLConfig.setPath(extractString(expressionNode));
-            return mutualSSLConfig;
+            return Optional.of(mutualSSLConfig);
+        }
+        if (expressionNode.kind() == SyntaxKind.SIMPLE_NAME_REFERENCE) {
+            diagnostics.add(C2CDiagnosticCodes
+                    .createDiagnostic(C2CDiagnosticCodes.FAILED_PORT_RETRIEVAL, expressionNode.location()));
```
Comment (anuruddhal) [inline c2c-util/src/main/java/io/ballerina/c2c/util/C2CVisitor.java:460]: This should be a generic diagnostic.

**Review by anuruddhal — CHANGES_REQUESTED** [review]

**Review by anuruddhal — APPROVED** [review]
