### PR TITLE
Fix mutual ssl retrieval in record form

### LINKED ISSUE #175: Mutual SSL path retrievals in a record form
**Description:**
$Subject

**Suggested Labels:**

**Suggested Assignees:**

**Affected Product Version:**

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

### PR DESCRIPTION
**Pull request by xlight05**
## Purpose
$Subject. 

Added Sample 9 test case to cover this use case.
```ballerina
  cert: {
      path: "./resource/ballerinaKeystore.p12",
      password: "ballerina"
  }
```

Resolves #175

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

### CODE REVIEW

File: c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+
+import static io.ballerina.c2c.KubernetesConstants.DOCKER;
+import static io.ballerina.c2c.KubernetesConstants.KUBERNETES;
+import static io.ballerina.c2c.test.utils.KubernetesTestUtils.deployK8s;
+import static io.ballerina.c2c.test.utils.KubernetesTestUtils.getCommand;
+import static io.ballerina.c2c.test.utils.KubernetesTestUtils.getExposedPorts;
+import static io.ballerina.c2c.test.utils.KubernetesTestUtils.loadImage;
+
+/**
+ * Test cases for sample 5.
```
Comment (anuruddhal) [inline c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java:48]: Change to sample9

File: c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
+/*
+ * Copyright (c) 2020, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
```
Comment (anuruddhal) [inline c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java:2]: 2021

File: c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+    @Test(groups = { "integration" })
+    public void deploySample() throws IOException, InterruptedException {
+        Assert.assertEquals(0, loadImage(DOCKER_IMAGE));
+        Assert.assertEquals(0, deployK8s(KUBERNETES_TARGET_PATH));
+        KubernetesTestUtils.deleteK8s(KUBERNETES_TARGET_PATH);
+    }
+
+    @AfterClass
+    public void cleanUp() throws KubernetesPluginException {
+//        KubernetesUtils.deleteDirectory(KUBERNETES_TARGET_PATH);
```
Comment (anuruddhal) [inline c2c-extension-test/src/test/java/io/ballerina/c2c/test/samples/Sample9Test.java:127]: Need to uncomment

**Review by anuruddhal — CHANGES_REQUESTED** [review]

**Review by anuruddhal — APPROVED** [review]
